#define MOTOR_LEFT_FRONT_DOWN 5
#define MOTOR_LEFT_FRONT_UP 4

#define MOTOR_RIGHT_FRONT_DOWN 2
#define MOTOR_RIGHT_FRONT_UP 3

#define MOTOR_RIGHT_BACK_DOWN 6
#define MOTOR_RIGHT_BACK_UP 7

#define MOTOR_LEFT_BACK_DOWN 9
#define MOTOR_LEFT_BACK_UP 8

#define ULTRASONIC_TRIG 11
#define ULTRASONIC_ECHO 10

